"""Frozen K=8 + future-occupancy recipe for the SA1 -> SA8 mainline."""

from dataclasses import replace

from rnn_car_modular.experiment_config import ExperimentConfig


ROOM_SIZE_BY_STAGE = {
    1: 10.0,
    2: 9.0,
    3: 8.5,
    4: 8.0,
    5: 7.5,
    6: 7.0,
    7: 6.5,
    8: 6.0,
}


BASE_CONFIG = ExperimentConfig(
    name="e2e_k8_future_frozen_base",
    description="Frozen K=8 E2E PPO + anti-spin A + dynamic future occupancy mainline.",
    task="Isaac-Navigation-Charge-VLP16-Curriculum-WD",
    curriculum_version="warp_drive_e2e_final20_v1",
    initial_stage=1,
    fixed_stage=True,
    scene_profile="warp_drive_e2e_final20_v1",
    obstacle_mode="rule_based",
    room_size=ROOM_SIZE_BY_STAGE[1],
    max_active_obstacles=20,
    use_action_history=False,
    reward_profile="clean_progress",
    algorithm="ppo",
    aux_profile="none",
    encoder_profile="e2e_frame_stack",
    critic_profile="symmetric",
    charge_encoder_mode="extractor_rnn",
    lidar_frame_stack=8,
    end_to_end_frame_stack=True,
    feat_norm=False,
    num_envs=1024,
    rollout_length=128,
    timesteps=270000,
    seed=42,
    lr=2e-4,
    rnn_lr=0.0,
    aux_lr=0.0,
    aux_lr_predict_head=0.0,
    aux_lr_fc_middle=0.0,
    aux_lr_fc_front=0.0,
    aux_lr_extractor=0.0,
    vf_coeff=0.5,
    gamma=0.99,
    gae_lambda=0.95,
    normalize_return=False,
    adv_norm_mode="full",
    value_init_bias=0.0,
    max_grad_norm=0.5,
    ppo_epochs=4,
    mini_batches=8,
    clip_eps=0.2,
    target_kl=0.015,
    value_clip_eps=0.2,
    ent_coeff=0.0,
    ent_coeff_linear=0.005,
    ent_coeff_angular=0.005,
    wd_update_clip=False,
    wd_update_monitor_only=False,
    wd_actor_update_clip=8.0,
    wd_critic_update_clip=30.0,
    wd_module_entropy_eps=1e-12,
    policy_loss_clamp=1e9,
    vf_term_clamp=1e9,
    hidden_dim=30,
    preprocess_dim=12,
    fc_dim=48,
    wd_middle_dim=32,
    rnn_type="RNN",
    predict_dim=7,
    aux_velocity_topk=0,
    aux_seq_len=15,
    aux_burn_in=0,
    aux_seq_batch_size=64,
    aux_grad_clip=0.5,
    zero_preprocess_feature_for_rl=False,
    lidar_no_noise=True,
    lidar_distance_bias=False,
    lidar_per_ring_bias=False,
    no_domain_randomization=True,
    enable_actuator_dr=False,
    obs_delay_steps=(0, 0),
    heading_stability_weight=0.0,
    penalty_speed_near_obs=-1.0,
    anti_spin_weight=0.15,
    anti_spin_hazard_distance=1.5,
    anti_spin_omega_threshold=0.8,
    anti_spin_progress_threshold=0.02,
    anti_spin_grace_steps=5,
    anti_spin_ramp_steps=5,
    anti_spin_yaw_grace_deg=180.0,
    anti_spin_yaw_ramp_deg=180.0,
    anti_spin_dt=0.2,
    future_occupancy_weight=0.10,
    future_occupancy_horizon_s=1.5,
    future_occupancy_samples=8,
    future_occupancy_safe_distance_m=1.0,
    future_occupancy_near_distance_m=3.0,
    future_occupancy_move_threshold_mps=0.1,
    reward_speed_v05=False,
    reward_mode="current",
    action_table_sample_size=0,
    log_interval=10,
    save_interval=50,
    checkpoint=None,
    no_resume_optimizer=True,
    tags=("e2e", "frame_stack8", "ppo", "clean_progress", "anti_spin_a", "future_occupancy", "final20"),
    notes="Frozen SA1-SA8 recipe. Only stage, room size, run name, and accepted parent checkpoint may change.",
)


def make_stage_config(stage: int) -> ExperimentConfig:
    if stage not in ROOM_SIZE_BY_STAGE:
        raise ValueError(f"stage must be in 1..8, got {stage}")
    return replace(
        BASE_CONFIG,
        name=f"e2e_sa{stage}_k8_future_frozen",
        description=f"Frozen K=8 + future-occupancy recipe on fixed SA{stage}.",
        initial_stage=stage,
        room_size=ROOM_SIZE_BY_STAGE[stage],
        tags=BASE_CONFIG.tags + (f"sa{stage}", "from_scratch" if stage == 1 else "warm_start"),
    )
