"""WD SA2 PPO, no aux training."""

from rnn_car_modular.experiment_config import ExperimentConfig

CONFIG = ExperimentConfig(
    name="wd_sa2_ppo_noaux",
    description="Fixed SA2, PPO-clip, WD sparse reward, aux disabled",
    task="Isaac-Navigation-Charge-VLP16-Curriculum-WD",
    curriculum_version="warp_drive_single_agent_v1",
    initial_stage=2,
    fixed_stage=True,
    obstacle_mode="rule_based",
    reward_profile="wd_sparse",
    algorithm_profile="ppo_clip",
    aux_profile="none",
    encoder_profile="wd_exact_rnn",
    critic_profile="symmetric",
    num_envs=1024,
    rollout_length=300,
    timesteps=180000,
    lr=1e-4,
    rnn_lr=0.0,
    vf_coeff=0.5,
    gamma=0.991,
    gae_lambda=0.95,
    normalize_return=True,
    value_init_bias=0.0,
    use_a2c=False,
    ppo_epochs=2,
    mini_batches=16,
    clip_eps=0.1,
    ent_coeff_linear=0.05,
    ent_coeff_angular=0.10,
    wd_update_clip=True,
    disable_aux_training=True,
    aux_seq_len=15,
    aux_seq_batch_size=256,
    aux_grad_clip=0.5,
    lidar_no_noise=True,
    action_table_sample_size=0,
    no_resume_optimizer=True,
    tags=("wd", "sa2", "ppo", "noaux"),
)
